perl.exe t\CellsApiTest.t
perl.exe t\CellsAutoFilterApiTest.t
perl.exe t\CellsAutoshapesApiTest.t
perl.exe t\CellsChartAreaApiTest.t
perl.exe t\CellsChartsApiTest.t
perl.exe t\CellsConditionalFormattingsApiTest.t
perl.exe t\CellsHypelinksApiTest.t
perl.exe t\CellsListObjectsApiTest.t
perl.exe t\CellsOleObjectsApiTest.t
perl.exe t\CellsPageBreaksApiTest.t
perl.exe t\CellsPageSetupApiTest.t
perl.exe t\CellsPicturesApiTest.t
perl.exe t\CellsPivotTablesApiTest.t
perl.exe t\CellsPropertiesApiTest.t
perl.exe t\CellsRangesApiTest.t
perl.exe t\CellsSaveAsApiTest.t
perl.exe t\CellsShapesApiTest.t
perl.exe t\CellsSparklineGroupsApi.t
perl.exe t\CellsTaskApiTest.t
perl.exe t\CellsWorkbookApiTest.t
perl.exe t\CellsWorksheetsApiTest.t
perl.exe t\CellsWorksheetValidationsApiTest.t
