=begin comment

Web API Swagger specification

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use AsposeCellsCloud::Configuration;
use AsposeCellsCloud::ApiClient;
use AsposeCellsCloud::CellsApi;
use AsposeCellsCloud::Object::ColumnsResponse;
my $config = AsposeCellsCloud::Configuration->new('base_url' => 'https://api-qa.aspose.cloud');
my $client = AsposeCellsCloud::ApiClient->new( $config);
my $api = AsposeCellsCloud::CellsApi->new($client);

my $access_token;

my $grant_type = 'client_credentials'; # replace NULL with a proper value
my $client_id = '91A2FD07-BBA1-4B32-9112-ABFB1FE8AEBD'; # replace NULL with a proper value
my $client_secret =  '0fbf678c5ecabdb5caca48452a736dd0'; # replace NULL with a proper value
my $result = $api->o_auth_post(grant_type => $grant_type, client_id => $client_id, client_secret => $client_secret);
$access_token =  $result->access_token;

printf $access_token;
# printf "\n";



1;
