name: Aspose Cells Cloud SDK 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events, but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      ProductClientId: ${{ secrets.PRODUCTCLIENTID }}
      ProductClientSecret: ${{ secrets.PRODUCTCLIENTSECRET }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Set up Strawberry Perl
        run: |
          choco install strawberryperl -y
        shell: powershell

      - name: Verify Perl installation
        run: |
          perl -v
        shell: cmd

      - name: Check cpan version
        run: cpan -v
        shell: cmd
      
      - name: Install Perl dependencies
        run: |
          cpan install URI::Query
          cpan install Log::Any
          cpan install JSON
          cpan install LWP::UserAgent          
        shell: cmd
        
      - name: Build SDK Package
        run: |
          perl Build.PL && ./Build
          cd examples
          perl .\Example_QuickStart.pl
